version: "3.8"

services:

  kimai2:
    image: kimai/kimai2:1.0.1
    container_name: kimai2
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
      APP_ENV: dev
      MAILER_FROM: ${MAILER_FROM}
    ports:
      - "81:8001"
    depends_on:
      - db

  db:
    container_name: kimai_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql/

volumes:
  db_data:
    driver_opts:
      type: none
      o: bind
      device: ./.docker/mysql/volume