version: "3.7"

services:

  kimai2:
    image: kimai/kimai2:0.9
    container_name: kimai2
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
      APP_ENV: dev
      MAILER_FROM: ${MAILER_FROM}
    ports:
      - 80:8001
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: kimai2_mysql
    environment:
      MYSQL_DATABASE: kimai
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_vol:/var/lib/mysql/

volumes:
  mysql_vol:
