version: "3.8"

services:

  kimai2:
    image: osioaliu/kimai2:1.14.3
    container_name: kimai2
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
      APP_ENV: dev
      MAILER_FROM: ${MAILER_FROM}
    ports:
      - "81:8001"
    depends_on:
      - db
    volumes:
      - composer_cache:/home/www/.composer:delegated

  db:
    container_name: kimai_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql/
      - db_dumps:/docker-entrypoint-initdb.d

volumes:
  db_data:
    driver_opts:
      type: none
      o: bind
      device: ./.docker/mysql/volume
  db_dumps:
    driver_opts:
      type: none
      o: bind
      device: ./.docker/mysql/db_dumps
  composer_cache:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.composer